package br.ufba.mata62.eleicoestransparentes.persistance.database.beans;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;


/**
 * @author niltonvasques
 *
 */
@DatabaseTable(tableName = "Bem")
public class ORMBem {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	private int id;
	
	@DatabaseField
	private String descricao;

	@DatabaseField
	private float valor;
	
	public ORMBem() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public float getValor() {
		return valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}
	
 
 }
