package br.ufba.eleicoestransparentes.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "AgenteEleitoral")
public class AgenteEleitoral {
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	private int id;
	
	private Pessoa pessoa;
	
	private Comite comite;
	
	public Class getTipoAgente(){
		if(pessoa != null) return Pessoa.class;
		if(comite != null) return Comite.class;
		return null;
	}
	
	public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Comite getComite() {
		return comite;
	}

	public void setComite(Comite comite) {
		this.comite = comite;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
