package br.ufba.eleicoestransparentes.model;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;


/**
 * @author niltonvasques
 *
 */
@DatabaseTable(tableName = "Bem")
public class Bem {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	private int id;
	
	@DatabaseField(width = 1000)
	private String descricao;

	@DatabaseField
	private float valor;
	
	@DatabaseField(foreign = true)
	private Candidato candidato;
	
	public Bem() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public float getValor() {
		return valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	public Candidato getCandidato() {
		return candidato;
	}

	public void setCandidato(Candidato candidato) {
		this.candidato = candidato;
	}
 
 }
